/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import sun.net.www.content.text.plain;

public class proyecto2 extends javax.swing.JFrame {

    /**
     * Creates new form proyecto2
     */
    public proyecto2() {

        Action action;
        action = new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent e){

                TableCellListener tcl = (TableCellListener)e.getSource();
                int cantidad;
                int fila = tcl.getRow();
                String[] registro = new String[6];
                String linea;
                String cantidadS;
                String valorS;

                if( tcl.getOldValue() != tcl.getNewValue() ) { // Si hay cambio
                    if ( tcl.getColumn() == 0 ) { // Cantidad

                        valorS = (String) jTable1.getValueAt(fila, 3);
                        if (valorS!=null ) {
                            cantidadS = (String) jTable1.getValueAt(fila,0);
                            cantidad  = Integer.parseInt(cantidadS);
                            jTable1.setValueAt(Double.parseDouble(valorS) * cantidad,fila,4); // Total
                        }

                    } else if ( tcl.getColumn() == 1 ) { // Codigo de producto

                        Producto producto = new Producto();
                        cantidadS = (String) jTable1.getValueAt(fila,0);
                        linea     = producto.buscarProducto((String) tcl.getNewValue());
                        registro  = linea.split("\\|");
                        jTable1.setValueAt(registro[1],fila,2); // Producto nombre
                        jTable1.setValueAt(registro[3],fila,3); // Precio U
                        if ( "".equals(cantidadS) || (cantidadS == null) ) {
                            cantidad = 1;
                            jTable1.setValueAt(String.valueOf(cantidad), fila, 0);
                        } else {
                            cantidad = Integer.parseInt(cantidadS);
                        }
                        jTable1.setValueAt(Double.toString(Double.parseDouble(registro[3]) * cantidad),fila,4); // Total

                    }
                }

            }

        };

        initComponents();
        TableCellListener tcl = new TableCellListener(jTable1, action);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fArticulos = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tACodigoM = new javax.swing.JTextField();
        tADescripcionM = new javax.swing.JTextField();
        tACostoM = new javax.swing.JTextField();
        tAPrecioM = new javax.swing.JTextField();
        tACantidadM = new javax.swing.JTextField();
        tATipoM = new javax.swing.JComboBox<>();
        bGuardarMercaderia = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fPedidos = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tPnombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tPdireccion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tPtelefono = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tPnit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        generarPedido = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Labelnumpedido = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Spinnerfecha = new javax.swing.JSpinner();
        fEntregas = new javax.swing.JFrame();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        buscarPedidoEntrega = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        bEnviar = new javax.swing.JButton();
        bEntregar = new javax.swing.JButton();
        bDevolucion = new javax.swing.JButton();
        fEntregasRegresar = new javax.swing.JButton();
        tIniciado = new javax.swing.JTextField();
        tEnviado = new javax.swing.JTextField();
        tEntregado = new javax.swing.JTextField();
        tPedidoEntrega = new javax.swing.JTextField();
        fDevolucion = new javax.swing.JFrame();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tDevolucionPedido = new javax.swing.JTextField();
        bArticulos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        fArticulos.setMinimumSize(new java.awt.Dimension(396, 350));

        jLabel1.setText("Ingreso de mercaderia");

        jLabel2.setText("Codigo");

        jLabel3.setText("Descripción");

        jLabel4.setText("Costo");

        jLabel5.setText("Precio");

        jLabel6.setText("Tipo");

        jLabel7.setText("Cantidad");

        tATipoM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ropa dama", "Ropa caballero", "Ropa niños", "Accesorio deportivo", "Joyeria" }));
        tATipoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tATipoMActionPerformed(evt);
            }
        });

        bGuardarMercaderia.setText("Guardar");
        bGuardarMercaderia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarMercaderiaActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fArticulosLayout = new javax.swing.GroupLayout(fArticulos.getContentPane());
        fArticulos.getContentPane().setLayout(fArticulosLayout);
        fArticulosLayout.setHorizontalGroup(
            fArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fArticulosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(fArticulosLayout.createSequentialGroup()
                        .addGroup(fArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(fArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tACodigoM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tADescripcionM, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(fArticulosLayout.createSequentialGroup()
                        .addGroup(fArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jButton2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(1, 1, 1)
                        .addGroup(fArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tACantidadM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tATipoM, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fArticulosLayout.createSequentialGroup()
                                .addComponent(tACostoM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tAPrecioM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bGuardarMercaderia, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        fArticulosLayout.setVerticalGroup(
            fArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fArticulosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(fArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tACodigoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tADescripcionM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tACostoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tAPrecioM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tATipoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(fArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tACantidadM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(bGuardarMercaderia))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        fPedidos.setMaximumSize(new java.awt.Dimension(560, 475));
        fPedidos.setMinimumSize(new java.awt.Dimension(560, 475));
        fPedidos.setPreferredSize(new java.awt.Dimension(560, 475));

        jLabel8.setText("Pedidos");

        jLabel9.setText("Numero");

        jLabel10.setText("Nombre");

        jLabel11.setText("Dirección");

        jLabel12.setText("Teléfono");

        jLabel13.setText("NIT");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cantidad", "Código", "Producto", "Precio U", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        generarPedido.setText("Generar pedido");
        generarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarPedidoActionPerformed(evt);
            }
        });

        jButton4.setText("Regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Labelnumpedido.setText("num");

        jLabel14.setText("Fecha de entrega:");

        Spinnerfecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_YEAR));

        javax.swing.GroupLayout fPedidosLayout = new javax.swing.GroupLayout(fPedidos.getContentPane());
        fPedidos.getContentPane().setLayout(fPedidosLayout);
        fPedidosLayout.setHorizontalGroup(
            fPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fPedidosLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Labelnumpedido)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fPedidosLayout.createSequentialGroup()
                        .addGroup(fPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(fPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tPdireccion)
                            .addComponent(tPnombre)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fPedidosLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tPtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tPnit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fPedidosLayout.createSequentialGroup()
                        .addGap(0, 42, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fPedidosLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Spinnerfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(generarPedido))))
        );
        fPedidosLayout.setVerticalGroup(
            fPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(Labelnumpedido))
                .addGap(18, 18, 18)
                .addGroup(fPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tPnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tPdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tPtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tPnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generarPedido)
                    .addComponent(jButton4)
                    .addComponent(jLabel14)
                    .addComponent(Spinnerfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        fEntregas.setMaximumSize(new java.awt.Dimension(450, 225));
        fEntregas.setMinimumSize(new java.awt.Dimension(450, 225));
        fEntregas.setPreferredSize(new java.awt.Dimension(450, 225));

        jLabel15.setText("Entregas");

        jLabel16.setText("Pedido");

        buscarPedidoEntrega.setText("Buscar");
        buscarPedidoEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPedidoEntregaActionPerformed(evt);
            }
        });

        jLabel17.setText("Iniciado");

        jLabel18.setText("Enviado");

        jLabel19.setText("Engregado");

        bEnviar.setText("Enviar");
        bEnviar.setEnabled(false);
        bEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnviarActionPerformed(evt);
            }
        });

        bEntregar.setText("Entregar");
        bEntregar.setEnabled(false);
        bEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEntregarActionPerformed(evt);
            }
        });

        bDevolucion.setText("Devolucion");
        bDevolucion.setEnabled(false);
        bDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDevolucionActionPerformed(evt);
            }
        });

        fEntregasRegresar.setText("Regresar");
        fEntregasRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fEntregasRegresarActionPerformed(evt);
            }
        });

        tIniciado.setEditable(false);

        tEnviado.setEditable(false);
        tEnviado.setToolTipText("");

        tEntregado.setEditable(false);

        javax.swing.GroupLayout fEntregasLayout = new javax.swing.GroupLayout(fEntregas.getContentPane());
        fEntregas.getContentPane().setLayout(fEntregasLayout);
        fEntregasLayout.setHorizontalGroup(
            fEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fEntregasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(fEntregasLayout.createSequentialGroup()
                        .addGroup(fEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tIniciado)
                            .addComponent(tEntregado)
                            .addComponent(tEnviado)
                            .addComponent(tPedidoEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                        .addGap(19, 19, 19)
                        .addGroup(fEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buscarPedidoEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bEntregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fEntregasRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        fEntregasLayout.setVerticalGroup(
            fEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fEntregasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(buscarPedidoEntrega)
                    .addComponent(tPedidoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(bEnviar)
                    .addComponent(tIniciado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(bEntregar)
                    .addComponent(tEnviado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(bDevolucion)
                    .addComponent(tEntregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(fEntregasRegresar)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel20.setText("Devoluciones");

        jLabel21.setText("Pedido");

        javax.swing.GroupLayout fDevolucionLayout = new javax.swing.GroupLayout(fDevolucion.getContentPane());
        fDevolucion.getContentPane().setLayout(fDevolucionLayout);
        fDevolucionLayout.setHorizontalGroup(
            fDevolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fDevolucionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fDevolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(fDevolucionLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tDevolucionPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        fDevolucionLayout.setVerticalGroup(
            fDevolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fDevolucionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fDevolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tDevolucionPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(242, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bArticulos.setText("Mercadería");
        bArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bArticulosActionPerformed(evt);
            }
        });

        jButton1.setText("Pedidos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Entregas");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(bArticulos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bArticulosActionPerformed
        this.setVisible(false);
        fArticulos.setVisible(true);
    }//GEN-LAST:event_bArticulosActionPerformed


    public int actualizarMercaderiaLista(int fila){
        int cantidad  = (int) jTable1.getValueAt(fila, 0);    // Cantidad);
        String codigo = (String) jTable1.getValueAt(fila, 1); // Codigo
        return 0;
    }

    private void bGuardarMercaderiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarMercaderiaActionPerformed
        String registro;
        Producto nuevo = new Producto();
        int resultado;

        resultado = nuevo.guardarMercaderia(
            tACodigoM.getText(),
            tADescripcionM.getText(),
            tACostoM.getText(),
            tAPrecioM.getText(),
            Integer.toString(tATipoM.getSelectedIndex()),
            tACantidadM.getText()
        );

        if( resultado == 1 ) {
            JOptionPane.showMessageDialog(rootPane, "El código ya existe");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Registro guardado");
        }

    }//GEN-LAST:event_bGuardarMercaderiaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        fArticulos.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fPedidos.setVisible(true);
        BufferedReader pedidoArchR;
        int pedido=0;
        String linea;
        try{
            pedidoArchR = new BufferedReader(new FileReader("pedidoNumero.txt")); // Lee el archivo
            int c=0;
            while((linea = pedidoArchR.readLine())!=null){
                pedido = (Integer.parseInt(linea))+1;
                c=1;
            }
            if(c==0){
                pedido = 1;
            }
            pedidoArchR.close();
        } catch (FileNotFoundException ex) {
            // Nop
        } catch (IOException ex) {
            // Nop
        }
        Labelnumpedido.setText(Integer.toString(pedido));
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tATipoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tATipoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tATipoMActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        fPedidos.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void generarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarPedidoActionPerformed

        String codigo, producto,preciou,total;
        String cant;
        String registro;
        String linea;
        int pedido = 0;
        BufferedReader pedidoArchR;
        BufferedWriter pedidoArch;

        // Obtener correlativo del pedido
        try{
            pedidoArchR = new BufferedReader(new FileReader("pedidoNumero.txt")); // Lee el archivo
            pedido      = (Integer.parseInt(pedidoArchR.readLine()))+1;
            pedidoArchR.close();
            pedidoArch  = new BufferedWriter(new FileWriter("pedidoNumero.txt"));  // Guarda el nuevo registro
            pedidoArch.write(Integer.toString(pedido));
            pedidoArch.flush();
            pedidoArch.close();
        } catch (FileNotFoundException ex) {
            // Nop
        } catch (IOException ex) {
            // Nop
        }

        // Encabezado del pedido
        try {
            pedidoArch  = new BufferedWriter(new FileWriter("pedidoEncabezado.txt",true));
//            Timestamp ts = new Timestamp((long) Spinnerfecha.getValue());
            registro = pedido+"|"+tPnombre.getText()+"|"+tPdireccion.getText()+"|"+tPtelefono.getText()+"|"+tPnit.getText();
            pedidoArch.write(registro);
            pedidoArch.newLine();
            pedidoArch.flush();
            pedidoArch.close();
        } catch (IOException ex) {
            // Nop
        }

        // Detalle del pedido
        try {
            pedidoArch  = new BufferedWriter(new FileWriter("pedidoDetalle.txt",true));
            for(int i = 0; i < 10; i++){
                cant     = (String) jTable1.getValueAt(i,0);
                codigo   = (String) jTable1.getValueAt(i,1);
                producto = (String) jTable1.getValueAt(i,2);
                preciou  = (String) jTable1.getValueAt(i,3);
                total    = (String) jTable1.getValueAt(i,4);
                if ( ! "".equals(codigo) && (codigo != null) ) {
                    registro = pedido+"|"+cant+"|"+codigo+"|"+producto+"|"+preciou+"|"+total;
                    pedidoArch.write(registro);
                    pedidoArch.newLine();
                }
            }
            pedidoArch.flush();
            pedidoArch.close();
        } catch (IOException ex) {
            // Nop
        }

        // Crear envio
        try {
            pedidoArch = new BufferedWriter(new FileWriter("envioDetalle.txt",true));
            registro   = pedido+"|"+(new Date()).getTime() +"|iniciado";
            pedidoArch.write(registro);
            pedidoArch.newLine();
            pedidoArch.flush();
            pedidoArch.close();
        } catch (IOException ex) {
            // Nop
        }

    }//GEN-LAST:event_generarPedidoActionPerformed

    private void buscarPedidoEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPedidoEntregaActionPerformed
        String linea;
        String[] registro = new String[3];
        String[] estado   = new String[3];
        String pedido     = tPedidoEntrega.getText();
        int posicion = 0;

        try{
            BufferedReader br = new BufferedReader(new FileReader("envioDetalle.txt"));
            while ( (linea = br.readLine() ) != null) {
                registro = linea.split("\\|");
                if( pedido.compareTo(registro[0]) == 0 ){
                    SimpleDateFormat sdfecha = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    estado[posicion]         = sdfecha.format(new Date( Long.parseLong(registro[1]) ));
                    posicion++;
                }
            }
            br.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "No se puede encontrar el archivo");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "No se puede leer el archivo");
        }

        switch (posicion) {
            case 0:
                JOptionPane.showMessageDialog(this, "No se encontró el pedido");
                break;
            case 1:
                bEnviar.setEnabled(true);
                bEntregar.setEnabled(false);
                bDevolucion.setEnabled(false);
                tIniciado.setText(estado[0]);
                tEnviado.setText("");
                tEntregado.setText("");
                break;
            case 2:
                bEnviar.setEnabled(false);
                bEntregar.setEnabled(true);
                bDevolucion.setEnabled(false);
                tIniciado.setText(estado[0]);
                tEnviado.setText(estado[1]);
                tEntregado.setText("");
                break;
            case 3:
                bEnviar.setEnabled(false);
                bEntregar.setEnabled(false);
                bDevolucion.setEnabled(true);
                tIniciado.setText(estado[0]);
                tEnviado.setText(estado[1]);
                tEntregado.setText(estado[2]);
                break;
        }

    }//GEN-LAST:event_buscarPedidoEntregaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        fEntregas.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void fEntregasRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fEntregasRegresarActionPerformed
        fEntregas.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_fEntregasRegresarActionPerformed

    private void bEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviarActionPerformed
        String registro;
        String pedido = tPedidoEntrega.getText();
        try {
            BufferedWriter pedidoArch = new BufferedWriter(new FileWriter("envioDetalle.txt",true));
            registro   = pedido+"|"+(new Date()).getTime() +"|enviado";
            pedidoArch.write(registro);
            pedidoArch.newLine();
            pedidoArch.flush();
            pedidoArch.close();
        } catch (IOException ex) {
            // Nop
        }
        bEnviar.setEnabled(false);
        bEntregar.setEnabled(false);
        bDevolucion.setEnabled(false);
        tIniciado.setText("");
        tEnviado.setText("");
        tEntregado.setText("");
        fEntregas.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_bEnviarActionPerformed

    private void bEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEntregarActionPerformed
        String registro;
        String pedido = tPedidoEntrega.getText();
        try {
            BufferedWriter pedidoArch = new BufferedWriter(new FileWriter("envioDetalle.txt",true));
            registro   = pedido+"|"+(new Date()).getTime() +"|entregado";
            pedidoArch.write(registro);
            pedidoArch.newLine();
            pedidoArch.flush();
            pedidoArch.close();
        } catch (IOException ex) {
            // Nop
        }
        bEnviar.setEnabled(false);
        bEntregar.setEnabled(false);
        bDevolucion.setEnabled(false);
        tIniciado.setText("");
        tEnviado.setText("");
        tEntregado.setText("");
        fEntregas.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_bEntregarActionPerformed

    private void bDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDevolucionActionPerformed
        fEntregas.setVisible(false);
        this.tDevolucionPedido.setText(tPedidoEntrega.getText());
        fDevolucion.setVisible(true);
    }//GEN-LAST:event_bDevolucionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proyecto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proyecto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proyecto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proyecto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proyecto2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Labelnumpedido;
    private javax.swing.JSpinner Spinnerfecha;
    private javax.swing.JButton bArticulos;
    private javax.swing.JButton bDevolucion;
    private javax.swing.JButton bEntregar;
    private javax.swing.JButton bEnviar;
    private javax.swing.JButton bGuardarMercaderia;
    private javax.swing.JButton buscarPedidoEntrega;
    private javax.swing.JFrame fArticulos;
    private javax.swing.JFrame fDevolucion;
    private javax.swing.JFrame fEntregas;
    private javax.swing.JButton fEntregasRegresar;
    private javax.swing.JFrame fPedidos;
    private javax.swing.JButton generarPedido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tACantidadM;
    private javax.swing.JTextField tACodigoM;
    private javax.swing.JTextField tACostoM;
    private javax.swing.JTextField tADescripcionM;
    private javax.swing.JTextField tAPrecioM;
    private javax.swing.JComboBox<String> tATipoM;
    private javax.swing.JTextField tDevolucionPedido;
    private javax.swing.JTextField tEntregado;
    private javax.swing.JTextField tEnviado;
    private javax.swing.JTextField tIniciado;
    private javax.swing.JTextField tPdireccion;
    private javax.swing.JTextField tPedidoEntrega;
    private javax.swing.JTextField tPnit;
    private javax.swing.JTextField tPnombre;
    private javax.swing.JTextField tPtelefono;
    // End of variables declaration//GEN-END:variables
}


